//------------------------------------------------------------------------------
// <auto-generated>
//     Αυτός ο κώδικας δημιουργήθηκε από εργαλείο.
//     Έκδοση χρόνου εκτέλεσης:2.0.50727.5420
//
//     Τυχόν αλλαγές σε αυτό το αρχείο ενδέχεται να προκαλέσουν εσφαλμένη συμπεριφορά και θα χαθούν αν
//     δημιουργηθεί ξανά ο κώδικας.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinMust.Properties {
	using System;
	
	
	/// <summary>
	///   Μια κλάση πόρων ισχυρού τύπου, για αναζήτηση μεταφρασμένων συμβολοσειρών κ.λπ.
	/// </summary>
	// Αυτή η κλάση δημιουργήθηκε αυτόματα από την κλάση StronglyTypedResourceBuilder
	// μέσω ενός εργαλείου όπως το ResGen ή το Visual Studio.
	// Για να προσθέσετε ή να καταργήσετε ένα μέλος, επεξεργαστείτε το αρχείο .ResX και στη συνέχεια εκτελέστε ξανά το ResGen
	// με την επιλογή /str ή επαναδομήστε το έργο VS.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Resources {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Resources() {
		}
		
		/// <summary>
		///   Επιστρέφει την αποθηκευμένη παρουσία ResourceManager που χρησιμοποιείται από αυτή την κλάση.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinMust.Properties.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Παρακάμπτει την ιδιότητα CurrentUICulture του τρέχοντος νήματος για όλες τις
		///   αναζητήσεις πόρων που χρησιμοποιούν αυτή την κλάση πόρων με αυστηρά καθορισμένο τύπο.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		internal static System.Drawing.Bitmap AC_80 {
			get {
				object obj = ResourceManager.GetObject("AC_80", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap AC_red_80 {
			get {
				object obj = ResourceManager.GetObject("AC_red_80", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap battery_80 {
			get {
				object obj = ResourceManager.GetObject("battery_80", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap battery_orange_80 {
			get {
				object obj = ResourceManager.GetObject("battery_orange_80", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap battery_red_80 {
			get {
				object obj = ResourceManager.GetObject("battery_red_80", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap logo {
			get {
				object obj = ResourceManager.GetObject("logo", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap RS232 {
			get {
				object obj = ResourceManager.GetObject("RS232", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap RS232_grey {
			get {
				object obj = ResourceManager.GetObject("RS232_grey", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap USB {
			get {
				object obj = ResourceManager.GetObject("USB", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap USB_grey {
			get {
				object obj = ResourceManager.GetObject("USB_grey", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	}
}
